import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/header'
import Footer from './components/footer'
import { Providers } from './provider'
import { Toaster } from 'sonner'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          <main className="flex min-h-screen flex-col items-center justify-between p-4 md:p-24 lg:p-24">
            {children}
          </main>
          <Footer />
        </Providers>
        <Toaster position="top-right" richColors />
      </body>
    </html>
  )
}
